### ISSUE TITLE
'NoneType' object has no attribute 'attributes'

### ISSUE THREAD

**Issue by vincenzosuraci** [peterbuga/HASS-sonoff-ewelink#100]
I'm getting these logs messages at startup:

```
2019-04-26 19:19:00 ERROR (Thread-2) [websocket] error from callback <bound method Sonoff.on_message of <custom_components.sonoff.Sonoff object at 0x729fb950>>: 'NoneType' object has no attribute 'attributes'
2019-04-26 19:19:02 ERROR (Thread-2) [websocket] error from callback <bound method Sonoff.on_message of <custom_components.sonoff.Sonoff object at 0x729fb950>>: 'NoneType' object has no attribute 'attributes'
2019-04-26 19:19:04 ERROR (Thread-2) [websocket] error from callback <bound method Sonoff.on_message of <custom_components.sonoff.Sonoff object at 0x729fb950>>: 'NoneType' object has no attribute 'attributes'
```

VS

**Comment by peterbuga** [comment]
Can you please get the longer error stack? the one usually found if you tail the HA log in command line. i can't figure it out when/why this one happens. pretty much it'll be perfect if you can give more details / any details regarding this. thnx

**Comment by vincenzosuraci** [comment]
@peterbuga sorry for being so short. Unfortunately, the log level was setup on `warning`. I got only these errors and no other additional info. Sometimes they appear, sometimes not (I rebooted Hassio and they disappeared). The effect of having these errors is that the voltage (measured in Volt) value of an eWelink component becomes `unknown`.

VS

**Comment by hdjweb** [comment]
I have the same identical problem so what I must do to solve it. It is true that sometimes current value is unknown.

**Comment by gx9001** [comment]
I have copied the patch on the _inti_.py file, and I don't have that message anymore, but I start to have this one instead 

Log Details (ERROR)
Tue Jul 02 2019 17:35:12 GMT-0500 (hora de verano central)
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method

**Comment by peterbuga** [comment]
@gx9001 doesn't look like a problem from my component it looks like something higher up (also the changes were very minimal), you should remove everything related to sonoff, download and add it again

**Comment by Bettinaglio** [comment]
Thanks a lot Peter. And thanks also for your component and work. 

---------------------------------------
Louis A. Bettinaglio
Via Lombardia 87, Corgeno  
I - 21029 Vergiate VA    
Tel: (39) 0331-948 538 
Fax: (39) 0331-948 898
louis@bettinaglio.com
---------------------------------------
Questo messaggio e gli allegati possono contenere informazioni riservate esclusivamente al destinatario. Il ricevente, se diverso dal destinatario è avvertito che qualunque utilizzo, divulgazione o copia  di questa comunicazione comporta violazione delle disposizioni di legge sulla tutela dei dati personali ed è pertanto rigorosamente vietata. Qualora il presente messaggio sia stato ricevuto per errore, Vi prego di informarmi immediatamente via e-mail a louis@bettinaglio.com

This e-mail and any files transmitted with it are confidential and may be privileged and are intended solely for the use of the individual or entity to whom they are addressed. Any unauthorised direct or indirect dissemination or copyng of this message and any attachments are strictly prohibited. If you have received the e-mail in error please inform me by e-mail to louis@bettinaglio.com

**Comment by Bettinaglio** [comment]
You’re right, not a problem due to your component Peter (Indexing errors and no parameter in view statement in group.yaml blocked the upgrade)

Have you got some other feedback from users of your component for occurring DataBase Errors due to the double under stroke in your __init__py?


I have the following continuing SQLITE errors in Home Assistant DataBase (does not harm the operability of the SONOFF switches (by the way; Sonoff Basic and Sonoff RF work both well with Firmware 3.01. You can update the database). 

14:28 components/recorder/__init__.py (ERROR)
Error executing query: (sqlite3.OperationalError) no such table: events [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)] [parameters: ('state_changed', '{"entity_id": "sensor.time_date", "old_state": {"entity_id": "sensor.time_date", "state": "14:27, 2019-08-20", "attributes": {"friendly_name": "Ora/D ... (465 characters truncated) ... :00", "last_updated": "2019-08-20T12:28:01.010066+00:00", "context": {"id": "7f1cdc8ae1124eaf89a1d8586d0d99c3", "parent_id": null, "user_id": null}}}', 'LOCAL', '2019-08-20 12:28:01.010268', '2019-08-20 12:28:28.822016', '7f1cdc8ae1124eaf89a1d8586d0d99c3', None)] (Background on this error at: http://sqlalche.me/e/e3q8)
14:28 components/recorder/util.py (ERROR)

Could that be the double underscore error which comes from the presence of "__" in the Sonoff Custom Component? 

See https://community.home-assistant.io/t/double-underscore-error-in-history-screen-after-update/109539

Thanks a lot for your nice work. Have a happy week, Peter!

----------------------------------------------------
Louis A. Bettinaglio
Via Lombardia 87, Corgeno  
I - 21029 Vergiate VA    
Tel: (39) 0331-948 538 
Fax: (39) 0331-948 898
louis@bettinaglio.com
----------------------------------------------------
Questo messaggio e gli allegati possono contenere informazioni riservate esclusivamente al destinatario. Il ricevente, se diverso dal destinatario è avvertito che qualunque utilizzo, divulgazione o copia  di questa comunicazione comporta violazione delle disposizioni di legge sulla tutela dei dati personali ed è pertanto rigorosamente vietata. Qualora il presente messaggio sia stato ricevuto per errore, Vi prego di informarmi immediatamente via e-mail a louis@bettinaglio.com

This e-mail and any files transmitted with it are confidential and may be privileged and are intended solely for the use of the individual or entity to whom they are addressed. Any unauthorised direct or indirect dissemination or copyng of this message and any attachments are strictly prohibited. If you have received the e-mail in error please inform me by e-mail to louis@bettinaglio.com

**Comment by peterbuga** [comment]
> Could that be the double underscore error which comes from the presence of "__" in the Sonoff Custom Component?

you mean `__` in the name? if so you can forget about it, because it's the base of python structure

the sqlite errors i'm pretty sure it's another problem completely not related to this component, i suggest completely reinstalling HA or double check the SD card if you're running of a raspPI  or something similar

**Comment by Bettinaglio** [comment]
Thanks a lot Peter, for your suggestions. Will do a complete new installation as soon as version 1.0 is out. On new Raspberry and new SD Card. In the meantime I continue ignoring the error warning. 

PS: Your integration works great.

----------------------------------------------------
Louis A. Bettinaglio
Via Lombardia 87, Corgeno  
I - 21029 Vergiate VA    
Tel: (39) 0331-948 538 
Fax: (39) 0331-948 898
louis@bettinaglio.com
----------------------------------------------------
Questo messaggio e gli allegati possono contenere informazioni riservate esclusivamente al destinatario. Il ricevente, se diverso dal destinatario è avvertito che qualunque utilizzo, divulgazione o copia  di questa comunicazione comporta violazione delle disposizioni di legge sulla tutela dei dati personali ed è pertanto rigorosamente vietata. Qualora il presente messaggio sia stato ricevuto per errore, Vi prego di informarmi immediatamente via e-mail a louis@bettinaglio.com

This e-mail and any files transmitted with it are confidential and may be privileged and are intended solely for the use of the individual or entity to whom they are addressed. Any unauthorised direct or indirect dissemination or copyng of this message and any attachments are strictly prohibited. If you have received the e-mail in error please inform me by e-mail to louis@bettinaglio.com
