### ISSUE TITLE
Question: Can ewelink block us?

### ISSUE THREAD

**Issue by neomvll** [peterbuga/HASS-sonoff-ewelink#103]
Hi,
Sorry about the noob question, but is there any possibility to ewelink block hass-sonoff-ewelink access??
Because of this component, now I'm looking to buy more sonoffs :)

**Comment by peterbuga** [comment]
hi @neomvll unfortunately like many other _implementations_ (or better said reverse engineering) of this kind it’s more of a problem of `when` than `if`!

in the same time there’s also a good part because the itead team hardcoded the authetification credentials in **all** the mobile apps (as far as i know) and to change the current flow will require for them to force **everyone** to update the mobile apps, i can’t even imagine the bad PR that would come out of a move like this 😬

it’s up to you if you if you want to invest further in these devices or not but in the same time I would highly recommand Shelly devices as they are waaay more friendlier 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
