### ISSUE TITLE
Question: E27?

### ISSUE THREAD

**Issue by neomvll** [peterbuga/HASS-sonoff-ewelink#104]
Hi guys,
Anyone was successful with E27?

**Comment by peterbuga** [comment]
after a quick google search i've seen that sonoff e27 refers to either `sonoff slampher` (fully supported) or `sonoff b1 bulb` (use **sonoff-bulb** branch - not merged currently to master - and read this thread too https://github.com/peterbuga/HASS-sonoff-ewelink/issues/34)

**Comment by neomvll** [comment]
Thanks for the quick reply!

I'll test a sonoff B1 at weekend and I just download the sonoff-bulb to put in my HASS, but I have others sonoffs (pow R2 and RF), and my RF not working with sonoff-bulb, only with normal sonoff.
How can I use all my sonoffs and the future B1? I need the 2 libs(sonoff and sonoff-bulb)?

**Comment by peterbuga** [comment]
@neomvll sonoff-bulb it's an extension of the master branch and should work just fine for all the other devices. you might experience the problems reported [here](https://github.com/peterbuga/HASS-sonoff-ewelink/issues/100) or [here](https://github.com/peterbuga/HASS-sonoff-ewelink/issues/101) that i haven't got the time to see what's wrong with them and fix them. 

if you experience other problems, please open another issue titled properly and try to give me as many error logs and describe what is happening / what is not working, a simple "not working" is not enough :P. otherwise feel free to add debug details to the issues mentioned above
