### ISSUE TITLE
HA 0.95.1 can't detect the component

### ISSUE THREAD

**Issue by max-rh** [peterbuga/HASS-sonoff-ewelink#122]
Hi Peter,
After upgrading to HA 0.95.1, it can't detect sonoff (I haven't change anything it the config before upgrading), any ideas ?

![image](https://user-images.githubusercontent.com/25219094/60374448-2fe06c00-9a0d-11e9-928f-036b86f3d79b.png)

**Comment by Bettinaglio** [comment]
Same to me. Went back to 0.94.4. Any suggestions?

**Comment by peterbuga** [comment]
out of curiosity i quickly updated to 0.95.4 in my test env i have no problem, everything works as before. any other helpful details regarding this ?

**Comment by Bettinaglio** [comment]
Peter, you're right, after checking and trying again probably the problem is not the Sonoff Custom Component (the Sonoff component not found error comes from the Check Home Assistant configuration against new release)  but it is much deeper. I use the old .states layout (not lovelace) and as soon I upgrade Hassio it looses all and every part of it besides the core configuration.yaml (groups, automation, scripts, ecc.). It did so in 0.95.0 and 0.95.4: 
![image](https://user-images.githubusercontent.com/40548048/60464057-d0bd6a00-9c4d-11e9-9ed5-a44e6cd1af84.png)

Probably this is not the right forum for that. Thanks a lot anyway for your nice Sonoff integration Peter.

**Comment by max-rh** [comment]
Thanks peter, sorry for this issue, it seems the issue was in HA 0.95.1 once i updated to 0.95.4 the issue was solved.
