### ISSUE TITLE
Feature Request: Ability to change id and name to Homeassistant

### ISSUE THREAD

**Issue by marrobHD** [peterbuga/HASS-sonoff-ewelink#125]
Ability to change id and name to Homeassistant.

**Comment by peterbuga** [comment]
can you please give a from->to example of what you try to achieve/change? i believe you might ignore a function already available in HA

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marrobHD** [comment]
I want to set the id from sonoff_id to sonoff_desklight

Am 28.07.2019 17:43 schrieb Peter Buga <notifications@github.com>:

can you please give a from->to example of what you try to achieve/change? i believe you might ignore a function already available in HA

Sent with GitHawk<http://githawk.com>

**Comment by peterbuga** [comment]
as I was thinking. unfortunately this has greater implications and far less uses just because you want to see it prettier in automations i assume (the entity names **must** be unique).
alternatively you can easily use https://www.home-assistant.io/components/switch.template/#copy-switch to generate a version as you require and hide the original one + general customization already available in HA
