### ISSUE TITLE
Switches do not show up in hass-cli but all other switches do 

### ISSUE THREAD

**Issue by haakonstorm** [peterbuga/HASS-sonoff-ewelink#132]
See:
https://github.com/home-assistant/home-assistant-cli/issues/272

**Comment by peterbuga** [comment]
TBH i really have no idea if this is a bug or not. never used hass-cli but in theory they should be easily listed just like all the others. 
i'm *injecting* the devices just like i've seen it done in other implementations, if someone could point me what i'm doing wrong i'm more than glad to change/fix it, but otherwise i won't spend too much time digging on this problem right now, bigger issues to fry 😬 

as a small test, try to enable the `debug` mode of this component as described in documentation, while doing this a fake sonoff device is added. if you can list this device than maybe hass-cli doesn't detect devices that are added a bit later on in the HA boot flow.
