### ISSUE TITLE
multible items not turned on/off by automation

### ISSUE THREAD

**Issue by skelgaard** [peterbuga/HASS-sonoff-ewelink#137]
Hey, i have several sonoff TH 10 connected and i have an automation that should turn on/off from 2-7 items at once...
If i do this with hue it works fine, but when sonoff i have from 1-5 that doesn't switch state...

**Comment by peterbuga** [comment]
duplicate, sorry https://github.com/peterbuga/HASS-sonoff-ewelink/issues/92

**Comment by skelgaard** [comment]
but there is no resolution on the other, so how can you close any of them ?

**Comment by peterbuga** [comment]
it's a pending issue that's why i closed this one (makes no sense to have multiple issue of the same problem). a quick dirty option would be to add a delay between the switches in automation, i would recommend 2+ seconds.
to be clear, the sonoff app api does not allow switching multiple entities in the same time (don't compare it with hue that's another thing)
