### ISSUE TITLE
Followed the instruction but nothing happens

### ISSUE THREAD

**Issue by Yonguelle** [peterbuga/HASS-sonoff-ewelink#138]
Hi guys! 

What I did:
1. added files __init__.py, sensor.py and switch.py to folder \custom_components\sonoff
2. added to configuration.yaml : 
```
sonoff:
  username: [mymail]
  password: [mypassword]
  scan_interval: 60 
  grace_period: 600
  api_region: 'eu' 
  entity_prefix: True 
  debug: False 
```

3. Restarted hassio
4. Literally nothing happens

Nothing on dashboard, nothing in services, no sign that I changed any config. Did I missed something?

**Comment by Yonguelle** [comment]
Home Assistant
0.98.4
Hassio installed on docker on Raspbian

**Comment by rickycraft** [comment]
It was related to python issues.
Due to various factors I ended up running hass.io on doker so everything now works fine

**Comment by surak** [comment]
I managed to run this on HA virtualenv, but I don't know what to do in order to run it on hass.io (or on containers, for that matter).

**Comment by peterbuga** [comment]
>but I don't know what to do in order to run it on hass.io (or on containers, for that matter).

@surak that makes at least 2 of us 😅 (i'm just kidding, i'll most likely be able to make it work, but i have no real usage to try/work on hass.io _or_ containers. i guess you'll have to figure this out on yourself)

i'm sorry but i'm closing this because i cannot support every install that's not working on 1st try :(
