### ISSUE TITLE
How to add switches into an Automation

### ISSUE THREAD

**Issue by NorthernMunkey** [peterbuga/HASS-sonoff-ewelink#171]
firstly thanks for the great work, i too don't want to loose the cloud enabled part of ewelink but want HA integration 
I'm looking to get the Sonoff switches that i see on the overview applied into various automation's.
E.g. when trigger sunset occurs do action switch sonoff light 1 on. etc.
but for the life of me i can't find the switch in actions ( as it's not a registered device/service etc)

how is everyone integrating their switches into their automation's

**Comment by peterbuga** [comment]
hi @NorthernMunkey 
just to be clear, because it's a bit fuzzy to me from the text above, do you have this component up&running? can you see/toggle the switches? 

if the answers from questions above are positive than i'm sorry to say to you but this is not the place to ask these kind of questions. there are countless already thread started on this subject just do a little bit of searching https://community.home-assistant.io
