### ISSUE TITLE
To Whom It May Concern: "Integration not found" or hanging on start

### ISSUE THREAD

**Issue by KMiNT21** [peterbuga/HASS-sonoff-ewelink#179]
Just note for users who can face the same. HA version: 0.99.3.
(I don't see any information about these requirements here.)

Start failed. Logs:

```
ModuleNotFoundError: No module named 'websocket'
2019-11-18 22:34:11 ERROR (MainThread) [homeassistant.setup] Setup failed for sonoff: Integration not found.

```

pip3 install websocket

Now it HANGING on start. No information. Set HA log module to debug, restart - nothing. Just freeze on start.

Many tests with config changing.
Nothing....

Only by examine sonoff module sources I've found:

`REQUIREMENTS        = ['uuid', 'websocket-client==0.54.0']`

So, we need these two modules to be installed:

pip3 install websocket websocket-client

May be modules must be installed during HA installation, I don't know. But I installed HA without virtual environment and had problems with not installed modules and I opened issue [#10482](https://github.com/home-assistant/home-assistant.io/issues/10482).

So I think this is not HASS-sonoff-ewelink issue. It is just note for people who can find it by google.

**Comment by peterbuga** [comment]
hi @KMiNT21 thanks for the comment
the `REQUIREMENTS = ['uuid', 'websocket-client==0.54.0']` it's specific to HA and it should pick it up and and install the required modules automatically. from previous experiences and because you installed HA without v.env (which is sooo wrong btw) i think you get into some kind of permissions problem that's blocking to install of required modules and hence the hanging (just a hunch anyway)

on top of that, what should i do with this "solved issue"? i cannot just leave it open without a specific thread, unless you have more to follow up on it

**Comment by KMiNT21** [comment]
> without v.env (which is sooo wrong btw) 

There is nothing wrong if it is server just for HA. :) Because this server IS the one environment.

>what should i do with this "solved issue"? i cannot just leave it open without a specific 

Sure. This thread must be closed now.

**Comment by kunsjef** [comment]
This helped me too. I run my HA in v.env but still i had to install websocket-client manually inside the v.env. 

Thanks for sharing!
