### ISSUE TITLE
turn off when router died?

### ISSUE THREAD

**Issue by gamot87** [peterbuga/HASS-sonoff-ewelink#294]
Its possible turn off the sonoff light switch if the router stop function or lose the internet connection?
im asking because i have some equipments with preset's to work at especific timetable windows and i realize the light swith still on when my router died.

**Comment by peterbuga** [comment]
@gamot87 unfortunately this plugin has not been updated in a long time due to time-constrains and with latest homeassistant changes i'm inclined to say it might not even work anymore.

please switch to https://github.com/AlexxIT/SonoffLAN as it has better support and in some cases even offline/BT features i think
