### ISSUE TITLE
Switching not working

### ISSUE THREAD

**Issue by dynawings** [peterbuga/HASS-sonoff-ewelink#5]
I created a dedicated account for this.
It reads the devices name and status correctly. The switching itself does not work.

**Comment by 2016for** [comment]
@peterbuga is updating code quite in realtime right now.

Please make sure you're using the latest code. Also would really appreciate if you could send some more info. Like what device, number of devices, any errors in the log?

Thanks

**Comment by dynawings** [comment]
1x Sonoff Basic
1x Sonoff S20 (I know it's not supported, but it's visible)

No errors in "Logbook" the logfiles, I could not check them yet. Still figuring that out, sorry.

**Comment by peterbuga** [comment]
hi @dynawings thanks for checking this out and taking the time to open the issue. 
unfortunately you probably end up in the middle of a debugging session because I don't have required devices and @2016for was helping me (and himself) to implement a new device model.

from the errors above it looks like your device has a different response than what i've seen so far therefore i would kindly ask you to follow the guide from here https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug so i can help further.

ps: be sure to check always for the latest version before posting an error, it's still a fresh project and i keep changing it 😄

**Comment by dynawings** [comment]
Looks like I can not run the debug script because hass.io has some restrictions. I will install the regular Home Assistant version tomorrow and give it another try.

I am willing to share the sonoff basic device with your eWeLink account if you're interested. In that case send me an email with your account name to wilco@dynawings.com

**Comment by peterbuga** [comment]
Thanks for the offer but the Sonoff Basic has been reported to work from multiple persons, I know it's structure already. If you keep having problems just keep sending the logs and again **don't forget to use the last version from here**

you can use this https://community.home-assistant.io/t/test-python-script-on-hassio/55268 to bypass some hassio restrictions.

**Comment by 2016for** [comment]
Better still just use your computer to get the json

**Comment by dynawings** [comment]
With the update to the latest version, it works, yeah. Thx for your support and for developing this!!!!

**Comment by dynawings** [comment]
I can confirm that the Sonoff S20 with firmware version 1.8.1 also works.
