### ISSUE TITLE
Use binding the same way as google home

### ISSUE THREAD

**Issue by dimitriy-k** [peterbuga/HASS-sonoff-ewelink#65]
Google home has eWelink binding. I think it will be better to use the same bindings api. Current imlementation by using mobile api does not work consistent, a lot of times it is not responding in HA.

**Comment by peterbuga** [comment]
Can you please elaborate the meaning of "eWelink binding"? do you mean API? if so i'm glad to let you know that thanks to @2016for who provided the documentation to official API from itead, the current implementation of `websocket` branch it's around 90% in line with it. 

which begs the question: have you tried the `websocket` branch yet? the state changes are almost instantly

**Comment by dimitriy-k** [comment]
https://www.itead.cc/blog/sonoff-work-with-google-home

I mean such integration. I don't know details, but somehow in Google home, they bind ewelink devices to google home, and it works without any issues. I expect it should be possible to "fake" it for HA.

**Comment by peterbuga** [comment]
I'm sorry but your request is a bit out of scope, I'll try not to go too deep into details but the way google home works is by contacting Google servers first AND THEN itead servers, and yes it works flawlessly because they invest a ton of money in it and they have full support from itead team :P. 

As an example, I was previously controlling sonoff devices using "fake" Alexa/Echo API, and I can assure you 100% it was not faster than current implementation. 

There are many other options for Sonoff (and alike) devices, this is just an option, unfortunately is not working for everyone...
