### ISSUE TITLE
Chacon devices

### ISSUE THREAD

**Issue by SeByDocKy** [peterbuga/HASS-sonoff-ewelink#90]
Hi,

Thanks a lot for your eWeLink's work.... works fine in HASS direct out of the box for a new baby like me. I got a request.... I got some chacon devices (https://www.chacon.be/fr/objets-connectes/47-chacon-module-eclairage-intelligent-wifi-5411478530145.html) ... Maybe I am wrong, but with such kind of webrequest.... I think it woud be possible to integrate these modules into HASS.

Are you interested with ?

**Comment by peterbuga** [comment]
hi there, thanks for another validation of my work! it really means a lot 😊!

regarding your proposal, i really don't know what to say, i'm already struggling to add new devices to this component as it is, mostly because itead team did a really sh*tty job maintaining a consistency between devices, it's not hard to control them (i already got the hang of it) but the hard part is to make a general template to fit them all nicely in HA.
right now i'm working on splitting the component into different packages per HA rules and hopefully i can submit it to the main project 🤞 i think a lot of people will appreciate this change!

i really don't know how i would be able the integrate `chacon` devices, with sonoff i had a couple of devices on hand to kickstart the reverse engineering otherwise it'll be extremely hard to explain the steps especially if you have no experience regarding it (no offence).

i was keep thinking to open a patreon.com account and hopefully get funds to buy various smart devices and to be able to add them in HA, but i'm not very sure people will be willing to invest in this kind of stuff (a person was kind enough though to this and I'm grateful for it!) even if it's a small amount per person.

if you want to continue this discussion, please look me up on http://community.home-assistant.io/ (same username) as it's easier to chat there. feel free to close this issue as it's not quite related to this project...
